# Site title/网站标题
title: "Jeff Duan's Blog"

# A description of your site for social meta tag and search engines/网站描述
description: "Jeff Duan's Blog - record and share your learning process."

# The base hostname & protocol of your site for where absolute urls are needed/网址
url: "http://Jeff-Duan.github.io"

# The subpath of your site, e.g. /blog, for generating urls
baseurl: ""

# The site cover image on the home page/封面图片
image: ""

# The shortname for your Disqus site to enable comments/您的Disqus网站简称
disqus_shortname:

# Your Google Analytics tracking code
google_analytics_tracking_id: ""

# Site navigation/网站导航
nav:
  - title: "Home"
    url: "/"
  - title: "Talks"
    url: "/talks"
  - title: "Downloads"
    url: "/downloads"
  - title: "About"
    url: "/about"

# Author information
author:
  name: Jeff-Duan
  bio: I'm Jeff-Duan.
  avatar: /static/images/Jeff-Duan.jpeg

# The "read next" posts to recommend at the bottom of each post/帖子底部添加"可能喜欢的其他帖子"
recommended_posts:
  - url: "/blog/2019/03/23/opening/"

# Extra Open Graph and Twitter Cards settings for social sharing

# Fallback og:image when no page.image or site.image. Facebook requires image be
# at least 200 x 200 pixels.
og_image:

# twitter:site. Your Twitter username without "@"
twitter_site: duanjianhui

Encoding: "utf-8"
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
gems:
  - jekyll-redirect-from
